test = {   'name': 'q16',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> len(model_proportions) % 2 == 0\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(np.unique(model_proportions)) == 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum(model_proportions) == 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(simulation_proportion,float)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 <= one_test_statistic <= 20\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
