test = {   'name': 'q25',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> type(sampling_q5) == int\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 < sampling_q5 < 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sampling_q5 != 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sampling_q5 != 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sampling_q5 != 3\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
