test = {   'name': 'q27',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> type(sampling_q7) == int\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 < sampling_q7 < 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sampling_q7 != 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sampling_q7 != 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sampling_q7 != 4\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
