test = {   'name': 'q31',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> len(some_functions) == 3\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> callable(some_functions.item(0))\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> callable(some_functions.item(1))\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> callable(some_functions.item(2))\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
