test = {   'name': 'q54',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> 0 < new_predict < 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> new_predict != 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> new_predict != 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> new_predict != 3\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
