test = {   'name': 'q14',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> 0 < q1_4 < 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_4 != 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_4 != 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_4 != 4\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
