test = {   'name': 'q26',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> statement_1 == True\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> statement_2 == False\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> statement_3 == True\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> statement_4 == False\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
