test = {   'name': 'q1_7',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(q1_7_80, int)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(q1_7_90, int)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(q1_7_99, int)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_7_80 in [1, 2, 3]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_7_90 in [1, 2, 3]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_7_99 in [1, 2, 3]\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
